{{- if .Values.apic_exporters.enabled }}
{{- if .Values.apic_exporters.exporter_types }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apic-exporters-deployment
  namespace: monsoon3
  labels:
    system: openstack
    service: metrics
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: apic-exporters
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: apic-exporters-etc
          configMap:
            name: apic-exporters
      containers:
        - name: apic-exporters
          imagePullPolicy: IfNotPresent
          image: {{ .Values.apic_exporters.docker_repo }}/infrastructure-exporters:{{ .Values.apic_exporters.image_version | replace "string:" "" }}
          args:
            - -c
            - /apic-exporters-etc/config-apic-exporters.yaml
          {{- if .Values.apic_exporters.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.apic_exporters.resources.requests.memory | quote }}
            limits:
              memory: {{ .Values.apic_exporters.resources.limits.memory | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: /apic-exporters-etc
              name: apic-exporters-etc
          ports:
            - name: metrics
              containerPort: {{ .Values.apic_exporters.prometheus_port }}
{{- end }}
{{- end }}
