{{- if .Values.apic_exporters.enabled }}
{{ $v := .Values.aci.apic_hosts | split ":" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apic-exporters
  namespace: monsoon3
  labels:
    system: openstack
    service: metrics
    component: configuration
{{- if .Values.apic_exporters.exporter_types }}
data:
  config-apic-exporters.yaml: |
    prometheus_port: {{ .Values.apic_exporters.prometheus_port }}
    log_level: {{ .Values.apic_exporters.device_information.log_level }}
    device_information:
      hostname: {{ $v._0 | quote}}
      username: {{ .Values.aci.apic_user }}
      password: {{ .Values.aci.apic_password }}
      tenant_name: {{ .Values.aci.apic_tenant_name }}
      proxy: {{- range $key, $val := .Values.apic_exporters.device_information.proxy }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    exporter_types:
      {{- range $exporter_type_values := .Values.apic_exporters.exporter_types  }}
      {{ $exporter_type_values.name }}:
        name: {{ $exporter_type_values.name | quote }}
      {{- range $key, $val := $exporter_type_values }}
      {{ if eq $key "collector" }}
        {{ $key }}:
          {{- range $listitem := $val }}
          - {{ $listitem }}
          {{- end}}
      {{ else }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
