{{- if .Values.snmp_exporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter
  labels:
    system: openstack
    service: metrics
data:
{{- range $config := .Values.snmp_exporter.maia_snmp_config }}
  {{ $config.name }}.yaml: |
{{ include (print "maia/templates/_snmp-exporter-" $config.configname ".yaml.tpl") . | indent 4 }}
      version: {{ $config.version }}
      auth:
        {{- if $config.community }}
        community: {{ $config.community }}
        {{- end }}
        {{- if $config.username }}
        username: {{ $config.username }}
        {{- end }}
        {{- if $config.password }}
        password: {{ $config.password }}
        {{- end }}
        {{- if $config.auth_protocol }}
        auth_protocol: {{ $config.auth_protocol }}
        {{- end }}
        {{- if $config.priv_protocol }}
        priv_protocol: {{ $config.priv_protocol }}
        {{- end }}
        {{- if $config.security_level }}
        security_level: {{ $config.security_level }}
        {{- end }}
        {{- if $config.priv_password }}
        priv_password: {{ $config.priv_password }}
        {{- end }}
{{- end }}
{{- range $config := .Values.arista.switches }}
  {{ $config.name }}.yaml: |
{{ include (print "maia/templates/_snmp-exporter-arista.yaml.tpl") . | indent 4 }}
      version: {{ $.Values.snmp_exporter.arista_version }}
      auth:
        community: {{ $.Values.snmp_exporter.arista_community }}
{{- end }}
{{- end }}
