dependencies:
  - name: cloudprober-exporter
    repository: file://vendor/cloudprober-exporter
    version: 1.0.0
    condition: cloudprober-exporter.enabled
  - name: netapp-exporter
    repository: file://vendor/netapp-exporter
    version: 0.0.1
    condition: netapp-exporter.enabled
  - name: apic_exporters
    repository: file://vendor/apic_exporters
    version: 1.0.0
    condition: apic_exporters.enabled
