apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iris-api

spec:
  tls:
     - secretName: iris
       hosts: [{{ .Values.api.ingress.host }}]
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: iris-api
              servicePort: 80

