apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: prometheus-alertmanager
  annotations:
    vice-president: {{ default false .Values.vice_president | quote }}
    disco: {{ default false .Values.disco | quote }}

spec:
  tls:
     - secretName: prometheus-alertmanager
       hosts: [alertmanager.{{ required "missing .Values.global.region" .Values.global.region }}.{{ required "missing .Values.global.domain" .Values.global.domain}}]
  rules:
    - host: alertmanager.{{ required "missing .Values.global.region" .Values.global.region }}.{{ required "missing .Values.global.domain" .Values.global.domain}}
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-alertmanager
            servicePort: 9093
