vcenter_nanny:
  enabled: False
  docker_repo: DEFINED-IN-REGION-CHART
  image_version: DEFINED-IN-REGION-CHART
  debug: True
  # dry run mode, i.e. just pretend to cleanup the entries
  dry_run: true
  # power off machines discovered as orphaned
  power_off: false
  # unregister machines discovered as orphaned
  unregister: false
  # delete machines discovered as orphaned
  delete: false
  # detach discovered ghost volumes
  detach_ghost_volumes: false
  # detach discovered ghost ports
  detach_ghost_ports: false
  # how many ghost volumes or ports to detach at maximum - if more: deny to delete any
  detach_ghost_limit: 3
  # enable or disable volume attachment consistency check
  vol_check: false
  # run the db cleanup every n minutes
  interval: 720
  # really delete entities after how many iterations
  iterations: 14

# these are used by the vcenter-nanny, but set during deployment via helm --set-string
from_cinder:
  global:
    dbPassword: "will_be_set_by_helm_deployment"
from_nova:
  global:
    dbPassword: "will_be_set_by_helm_deployment"
current_region: "will_be_set_by_helm_deployment"

vcenter_nanny_consistency:
  enabled: False
  # this one we use from the vcenter nanny entry above as we use the same docker repo
  # docker_repo: DEFINED-IN-REGION-CHART
  consistency_image_version: DEFINED-IN-REGION-CHART
  debug: True
  # dry run mode, i.e. just pretend to cleanup the entries
  dry_run: true
  # run the db consistency check every minutes
  interval: 60
  # warn after how many iterations
  iterations: 3
  # maximum number of inconsistent volumes to fix automatically - otherwise fixing will be denied
  fix_limit: 10
  # if cells are enabled, put the VCENTER_CONSISTENCY_HOST here as a reference the az with an own cell db - False if not relevant
  cell2_vc: False

vcenter_exporter:
  enabled: False
  docker_repo: DEFINED-IN-REGION-CHART
  image_version: DEFINED-IN-REGION-CHART
  resources:
    enabled: True
    requests:
      memory: DEFINED-IN-REGION-CHART
    limits:
      memory: DEFINED-IN-REGION-CHART
  prometheus_port: DEFINED-IN-REGION-CHART
  device_information:
      hostname: provided-by-vcenter-operator
      username: provided-by-vcenter-operator
      password: provided-by-vcenter-operator
      port: 443
      ignore_ssl: "true"
      availability_zone: DEFINED-IN-REGION-CHART
      log_level: INFO
  exporter_types:
    vcapiandversions:
      name: vcapiandversions
      enabled: False
      collection_interval: 120
      collector: DEFINED-IN-REGION-CHART
    vccustomerdsmetrics:
      name: vccustomerdsmetrics
      enabled: False
      collection_interval: 120
      ignore_ds_match_regex: DEFINED-IN-REGION-CHART
      vc_cluster_match_regex: DEFINED-IN-REGION-CHART
      collector: DEFINED-IN-REGION-CHART
    vccustomervmmetrics:
      name: vccustomervmmetrics
      enabled: False
      collection_interval: 120
      vc_cluster_match_regex: DEFINED-IN-REGION-CHART
      shorter_names_regex: DEFINED-IN-REGION-CHART
      ignore_vm_match_regex: DEFINED-IN-REGION-CHART
      collector: DEFINED-IN-REGION-CHART
      vm_metrics: DEFINED-IN-REGION-CHART

vasa_exporter:
  enabled: False
  docker_repo: DEFINED-IN-REGION-CHART
  image_version: DEFINED-IN-REGION-CHART
  prometheus_port: 9102
  vp_port: 8143
  vp_user: administrator
  vp_pass: DEFINED-IN-REGION-CHART
  vvol_user: DEFINED-IN-REGION-CHART
  vvol_pass: DEFINED-IN-REGION-CHART
