dependencies:
  - name: api
    repository: "file://charts/api"
    version: 0.1.0
    condition: api.enabled
    tags:
      - api

  - name: ui
    repository: "file://charts/ui"
    version: 0.1.0
    condition: ui.enabled
    tags:
      - ui
