vcenter_exporter:
  enabled: False
  docker_repo: DEFINED-IN-REGION-CHART
  image_version: DEFINED-IN-REGION-CHART
  resources:
    enabled: True
    requests:
      memory: DEFINED-IN-REGION-CHART
    limits:
      memory: DEFINED-IN-REGION-CHART
  log_level: INFO
  prometheus_port: DEFINED-IN-REGION-CHART
  device_information:
      hostname: provided-by-vcenter-operator
      username: provided-by-vcenter-operator
      password: provided-by-vcenter-operator
      port: 443
      ignore_ssl: "true"
      availability_zone: DEFINED-IN-REGION-CHART
  exporter_types:
    vcapiandversions:
      name: vcapiandversions
      enabled: False
      collection_interval: 120
      collector: DEFINED-IN-REGION-CHART
    vccustomerdsmetrics:
      name: vccustomerdsmetrics
      enabled: False
      collection_interval: 120
      ignore_ds_match_regex: DEFINED-IN-REGION-CHART
      vc_cluster_match_regex: DEFINED-IN-REGION-CHART
      collector: DEFINED-IN-REGION-CHART
    vccustomervmmetrics:
      name: vccustomervmmetrics
      enabled: False
      collection_interval: 120
      vc_cluster_match_regex: DEFINED-IN-REGION-CHART
      shorter_names_regex: DEFINED-IN-REGION-CHART
      ignore_vm_match_regex: DEFINED-IN-REGION-CHART
      collector: DEFINED-IN-REGION-CHART
      vm_metrics: DEFINED-IN-REGION-CHART