apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reverse-proxy
  annotations:
    disco: "true"
    vice-president: "true"
  labels:
    app: reverse-proxy
spec:
  rules:
  - host: {{ .Values.concourse.concourse.web.externalDomain }}
    http:
      paths:
      - backend:
          serviceName: reverse-proxy
          servicePort: 8080
  tls:
  - hosts:
    - {{ .Values.concourse.concourse.web.externalDomain }}
    secretName: concourse-web-tls
