apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  template:
    metadata:
      labels:
        name: reverse-proxy
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/reverse-proxy-config.yaml") . | sha256sum }}
    spec:
      containers:
      - image: hub.global.cloud.sap/d074427/openresty-nginx-jwt:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          limits:
              cpu: 300m
              memory: 512Mi
          requests:
              cpu: 200m
              memory: 256Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
      volumes:
      - name: config
        configMap:
          name: reverse-proxy
