{{- if and .Values.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "name" . }}
  name: {{ template "name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ required ".Values.rbac.serviceAccountName missing" .Values.rbac.serviceAccountName }}
    namespace: kube-system
{{- end -}}
