kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: iris

spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.ui.replica_count }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: iris
    spec:
      # The preStop hook below sleeps 30 seconds, extend the gracePeriod accordingly
      terminationGracePeriodSeconds: 60
      containers:
        - name: web
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{.Values.ui.pullPolicy}}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REGION
              value: {{ .Values.region }}
            - name: IDENTITY_ENDPOINT
              value: {{ .Values.ui.identity_endpoint }}
            - name: AUTH_SCOPE_DOMAIN
              value: {{ .Values.ui.auth_scope_domain }}
            - name: AUTH_SCOPE_PROJECT
              value: {{ .Values.ui.auth_scope_project }}
          livenessProbe:
            httpGet:
              path: /system/liveliness
              port: 80
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /system/readiness
              port: 80
            timeoutSeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                #Give the ingress some time to reload its config
                command: ["/bin/sh","-c","sleep 30"]
