{{- range $index, $cluster := .Values.clusters }}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: swift-proxy-{{$cluster.name}}
  labels:
    release: "{{$.Release.Name}}"
    os-cluster: {{$cluster.name}}
spec:
  revisionHistoryLimit: 5
  replicas: {{$cluster.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq $cluster.replicas 1.0 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
      maxSurge: 2
  selector:
    matchLabels:
      component: swift-proxy-{{$cluster.name}}
  template:
    metadata:
      labels:
        component: swift-proxy-{{$cluster.name}}
      annotations:
        checksum/swift-cluster.etc: {{ include "swift/templates/etc/cluster-configmap.yaml" $ | sha256sum }}
        {{- include "swift_conf_annotations" $ | indent 8 }}
        checksum/swift.bin: {{ include "swift/templates/bin-configmap.yaml" $ | sha256sum }}
        {{- include "swift_ring_annotations" $ | indent 8 }}
    spec:
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-swift-{{$cluster.name}}
        - name: swift-bin
          configMap:
            name: swift-bin
        - name: swift-etc
          configMap:
            name: swift-etc
        - name: swift-etc-cluster
          configMap:
            name: swift-etc-{{$cluster.name}}
        - name: swift-account-ring
          configMap:
            name: swift-account-ring
        - name: swift-container-ring
          configMap:
            name: swift-container-ring
        - name: swift-object-ring
          configMap:
            name: swift-object-ring
      containers:
        - name: proxy
          image: {{ include "swift_image" $ }}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /usr/bin/swift-start
            - proxy-server
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            {{- if $.Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: swift.DSN.public
            {{- end }}
          {{- if $.Values.resources.enabled }}
          resources:
            # observed usage: CPU = 300m-2500m, RAM = 450-800 MiB
            requests:
              cpu: "2000m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "1024Mi"
          {{- end }}
          volumeMounts:
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-etc-cluster
              name: swift-etc-cluster
            - mountPath: /swift-rings/account
              name: swift-account-ring
            - mountPath: /swift-rings/container
              name: swift-container-ring
            - mountPath: /swift-rings/object
              name: swift-object-ring
        - name: nginx
          image: {{$.Values.global.imageRegistry}}/monsoon/swift-nginx:{{$.Values.image_version_nginx}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/sh
            - /swift-bin/nginx-start
          {{- if $.Values.resources.enabled }}
          resources:
            # observed usage: CPU = 10m-500m, RAM = 20-50 MiB
            requests:
              cpu: "1000m"
              memory: "100Mi"
            limits:
              cpu: "1000m"
              memory: "100Mi"
          {{- end }}
          volumeMounts:
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-etc-cluster
              name: swift-etc-cluster
            - mountPath: /tls-secret
              name: tls-secret
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{$cluster.proxy_public_port}}
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: {{tuple $cluster $.Values | include "swift_endpoint_host"}}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
        {{- if $.Values.health_statsd }}
        - name: collector
          image: {{ include "swift_image" $ }}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /usr/bin/swift-start
            - health-statsd
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_PORT
              value: "9125"
            - name: LOG_LEVEL
              value: "info"
            - name: ADD_HOSTNAME_SUFFIX
              value: "true"
          {{- if $.Values.resources.enabled }}
          resources:
            # observed usage: CPU = 100m-300m, RAM = 20-85 MiB
            requests:
              cpu: "400m"
              memory: "150Mi"
            limits:
              cpu: "400m"
              memory: "150Mi"
          {{- end }}
          volumeMounts:
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-rings/account
              name: swift-account-ring
            - mountPath: /swift-rings/container
              name: swift-container-ring
            - mountPath: /swift-rings/object
              name: swift-object-ring
        {{- end}}
        - name: statsd
          image: prom/statsd-exporter:{{$.Values.image_version_auxiliary_statsd_exporter}}
          args: [ --statsd.mapping-config=/swift-etc/statsd-exporter.yaml ]
          {{- if $.Values.resources.enabled }}
          resources:
            # observed usage: CPU = 10m-100m, RAM = 550-950 MiB
            requests:
              cpu: "120m"
              memory: "1024Mi"
            limits:
              cpu: "120m"
              memory: "1024Mi"
          {{- end }}
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: 9102
          volumeMounts:
            - mountPath: /swift-etc
              name: swift-etc

---
{{end}}
